#!/bin/sh

echo "cl $*" >> $0.log
INPUTFILE=""
DEFINE=""
INCLUDE=""
SYSTEMLIBRARY="advapi32.lib Advapi32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib Ws2_32.lib"

getpdbfile()
{
	PDBFILE="${1%.*}.pdb"
}

for opt in $@; do
	case $opt in
		-o)
		shift
		OUTFILE="$1"
		getpdbfile $OUTFILE
		;;
		-g)
		;;
		-link)
		;;
		-dll)
		OUTTYPE="-link -dll"
		;;
		-Xlinker)
		;;
		--out-implib)
		;;
		-Xlinker)
		;;
		--enable-auto-image-base)
		;;
		-nostdlib)
		;;
		-shared)
		OUTTYPE="-link -dll"		
		;;
		-D*)
		DEFINE="$DEFINE $opt"
		;;
		-I*)
		INCLUDE="$INCLUDE $opt"
		;;
		-c)
		;;
		-*)
		echo "igrone option $opt"
		;;
		*.obj|*.c|*.cpp|*.h|*.hpp|*.lib)
		INPUTFILE="$INPUTFILE $opt"
		;;
		*.*)
		echo "igrone file $opt"
		;;
		*)
		echo "invalid argument $opt"
		break
		;;
	esac
	shift
done

if test -z $OUTTYPE && test -z $OUTFILE ; then
	cmdargs="-g -c $INPUTFILE $DEFINE $INCLUDE"
else
	cmdargs="-o $OUTFILE $INPUTFILE $SYSTEMLIBRARY $OUTTYPE"
fi

echo $cmdargs>>$0.log
${MSVC}/cl $cmdargs >> $0.log