#!/bin/sh

echo "cl $*" >> $0.log
LOCAL_INPUTFILE=""
LOCAL_DEFINE=""
LOCAL_INCLUDE=""
LOCAL_SYSTEMLIBRARY="advapi32.lib Advapi32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib Ws2_32.lib"
LOCAL_COMPILE=""

getpdbfile()
{
	LOCAL_PDBFILE="${1%.*}.pdb"
}

for opt in $@; do
	case $opt in
		-o)
		shift
		LOCAL_OUTFILE="$1"
		getpdbfile $LOCAL_OUTFILE
		;;
		-g)
		;;
		-link)
		;;
		-c)
		LOCAL_COMPILE="-c"
		;;
		-dll)
		LOCAL_OUTTYPE="-link -dll"
		;;
		-Xlinker)
		;;
		--out-implib)
		;;
		-Xlinker)
		;;
		--enable-auto-image-base)
		;;
		-nostdlib)
		;;
		-shared)
		LOCAL_OUTTYPE="-link -dll"		
		;;
		-D*)
		LOCAL_DEFINE="$LOCAL_DEFINE $opt"
		;;
		-I*)
		LOCAL_INCLUDE="$LOCAL_INCLUDE $opt"
		;;
		-c)
		;;
		-*)
		echo "igrone option $opt"
		;;
		*.obj|*.c|*.cpp|*.h|*.hpp|*.lib)
		if [ "x$LOCAL_OUTFILE" != "x$opt" ]; then
			LOCAL_INPUTFILE="$LOCAL_INPUTFILE $opt"
		fi
		;;
		*.*)
		echo "igrone file $opt"
		;;
		*)
		echo "invalid argument $opt"
		break
		;;
	esac
	shift
done

if test -z $LOCAL_COMPILE ; then
	cmdargs="-o $LOCAL_OUTFILE $LOCAL_INPUTFILE $LOCAL_SYSTEMLIBRARY $LOCAL_INCLUDE $LOCAL_OUTTYPE"
else
	cmdargs="-g -c $LOCAL_INPUTFILE $LOCAL_DEFINE $LOCAL_INCLUDE"	
fi

echo "${MSVC}"/cl $cmdargs>>$0.log
"${MSVC}"/cl $cmdargs>>$0.log