#!/bin/sh
echo "$0 $*"
echo "$0 $*" >>$0.log
#如果打包其他格式的文件将被忽略
#如果打包其他的文件将导致使用这个库时出现 
#error : member at n is not an ELF object
#下面将忽略除.o的一切文件作为输入文件
ar_OPT=""
unset aroutputFILE
while [ $# -gt 0 ] ;
do
	case $1 in
		*.o)
		ar_OPT="${ar_OPT} $1"
		;;
		*.a)
		if [ -z $aroutputFILE ] ; then
			ar_OPT="${ar_OPT} $1"
			aroutputFILE=$1					
		else
			echo "Warning ar Igrone file : $1"
		fi
		;;
		*.*)
		echo "Warning ar Igrone file : $1"
		;;
		*)
		ar_OPT="${ar_OPT} $1"
		;;
	esac
	shift
done
echo "${NDK_TOOLCHAINS}/bin/arm-linux-androideabi-ar $ar_OPT"
"${NDK_TOOLCHAINS}"/bin/arm-linux-androideabi-ar $ar_OPT